In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.lines import Line2D

import warnings
warnings.filterwarnings("ignore", "is_categorical_dtype")
warnings.filterwarnings("ignore", "use_inf_as_na")

font = {'size'   : 12}

matplotlib.rc('font', **font)

In [2]:
data_dir = "/homes/ukumaras/Projects/fast"

twitter_base = pd.read_csv(f"{data_dir}/results_remote_new/CkQST_KNN_NO_twitter_maxk3_ckqst.csv")
twitter_adopt = pd.read_csv(f"{data_dir}/results_final/AdoptCkQST_KNN_NO_twitter_adoptckqst.csv")
twitter_fast = pd.read_csv(f"{data_dir}/results_remote_new/FAST_KNN_NO_ObjIndex_twitter_maxk3_fast.csv")

df = pd.concat([twitter_base, twitter_adopt, twitter_fast])
df = pd.DataFrame(df).groupby(['name', 'num_queries']).mean().reset_index() #[df.num_queries == 5000000]
df['index'] = df['name'].apply(lambda x: x.split("_")[0])

df['dataset'] = df['name'].apply(lambda x: x.split("_")[-2])
df['num_queries'] = (df['num_queries'] / 1000000).astype(int)
df

,name,num_queries,creation_time,search_time,create_mem,search_mem,num_objects,k,create_object_mem,create_query_mem,create_query_idx_mem,create_object_idx_mem,search_query_idx_mem,search_object_idx_mem,search_object_mem,search_query_mem,knn_deg_ratio,knn_ar_thresh,index,dataset
0,AdoptCkQST_KNN_NO_twitter_adoptckqst,1,2.540843e+12,2.537858e+12,NaN,NaN,100000.0,5.0,52713904.0,5.102898e+08,5.984738e+08,137441800.0,5.984738e+08,273515792.0,52713904.0,5.102898e+08,NaN,NaN,AdoptCkQST,twitter
1,AdoptCkQST_KNN_NO_twitter_adoptckqst,2,3.428486e+12,2.741444e+12,NaN,NaN,100000.0,5.0,52695264.0,1.022753e+09,1.197137e+09,138120288.0,1.197137e+09,274825616.0,52695264.0,1.022753e+09,NaN,NaN,AdoptCkQST,twitter
2,AdoptCkQST_KNN_NO_twitter_adoptckqst,5,6.508237e+12,3.529487e+12,NaN,NaN,100000.0,5.0,52720936.0,2.553186e+09,2.989923e+09,138392776.0,2.989923e+09,276972024.0,52720936.0,2.553186e+09,NaN,NaN,AdoptCkQST,twitter
3,AdoptCkQST_KNN_NO_twitter_adoptckqst,10,1.016720e+13,5.849671e+12,NaN,NaN,100000.0,5.0,52732448.0,5.120362e+09,5.962560e+09,138052576.0,5.962560e+09,278164512.0,52732448.0,5.120362e+09,NaN,NaN,AdoptCkQST,twitter
4,CkQST_KNN_NO_twitter_maxk3_ckqst,1,2.365957e+12,2.464630e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CkQST,maxk3
5,CkQST_KNN_NO_twitter_maxk3_ckqst,2,3.611244e+12,3.673334e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CkQST,maxk3
6,CkQST_KNN_NO_twitter_maxk3_ckqst,5,5.772058e+12,5.104670e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CkQST,maxk3
7,CkQST_KNN_NO_twitter_maxk3_ckqst,10,1.026687e+13,7.520689e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CkQST,maxk3
8,CkQST_KNN_NO_twitter_maxk3_ckqst,20,2.032870e+13,1.701167e+10,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CkQST,maxk3
9,FAST_KNN_NO_ObjIndex_twitter_maxk3_fast,1,2.405256e+12,2.653669e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,5.0,FAST,maxk3
10,FAST_KNN_NO_ObjIndex_twitter_maxk3_fast,2,3.574575e+12,2.941714e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,5.0,FAST,maxk3
11,FAST_KNN_NO_ObjIndex_twitter_maxk3_fast,5,5.561423e+12,3.377492e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,5.0,FAST,maxk3
12,FAST_KNN_NO_ObjIndex_twitter_maxk3_fast,10,1.025647e+13,4.409423e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,5.0,FAST,maxk3
13,FAST_KNN_NO_ObjIndex_twitter_maxk3_fast,20,2.026793e+13,7.244550e+09,0.0,0.0,100000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,5.0,FAST,maxk3

### Create

In [3]:
create = pd.DataFrame(df.loc[:, ['index', 'num_queries', 'creation_time']])
create

         index  num_queries  creation_time
0   AdoptCkQST            1   2.540843e+12
1   AdoptCkQST            2   3.428486e+12
2   AdoptCkQST            5   6.508237e+12
3   AdoptCkQST           10   1.016720e+13
4        CkQST            1   2.365957e+12
5        CkQST            2   3.611244e+12
6        CkQST            5   5.772058e+12
7        CkQST           10   1.026687e+13
8        CkQST           20   2.032870e+13
9         FAST            1   2.405256e+12
10        FAST            2   3.574575e+12
11        FAST            5   5.561423e+12
12        FAST           10   1.025647e+13
13        FAST           20   2.026793e+13

In [4]:
out = create.pivot(index='num_queries', columns='index', values='creation_time').reset_index()
out.to_csv('out_numq.dat', header=False, index=False, sep='\t')

### Search

In [5]:
search = pd.DataFrame(df.loc[:, ['index', 'num_queries', 'search_time']])
search

         index  num_queries   search_time
0   AdoptCkQST            1  2.537858e+12
1   AdoptCkQST            2  2.741444e+12
2   AdoptCkQST            5  3.529487e+12
3   AdoptCkQST           10  5.849671e+12
4        CkQST            1  2.464630e+09
5        CkQST            2  3.673334e+09
6        CkQST            5  5.104670e+09
7        CkQST           10  7.520689e+09
8        CkQST           20  1.701167e+10
9         FAST            1  2.653669e+09
10        FAST            2  2.941714e+09
11        FAST            5  3.377492e+09
12        FAST           10  4.409423e+09
13        FAST           20  7.244550e+09

In [6]:
out = search.pivot(index='num_queries', columns='index', values='search_time').reset_index()
out.to_csv('out_numq.dat', header=False, index=False, sep='\t')